routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'TreeController@jsTree');
Route::get('/trees/connect', 'TreeController@connect');
Route::get('/trees/sortByLevel', 'TreeController@sortByLevel');
Route::get('/trees/sortByPosition', 'TreeController@index');
Route::post('/trees/connect', 'TreeController@edge');
Route::resource('trees', 'TreeController');

app/Edges.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Edges extends Model
{
    protected $fillable = [
        'id_vertex_child',
        'id_vertex_parent'
    ];

}

app/Tree.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tree extends Model
{
    protected $fillable = [
        'name',
        'position',
        'level'
    ];

    public static function allPositionDescending()
    {
        $tree = Tree::all();
        return $tree->sortBy('position');
    }

    public static function allLevelDescending()
    {
        $tree = Tree::all();
        return $tree->sortBy('level');
    }

    public static function addWithChangePositionOld($request) {
        $requestPosition = $request->input('position');
        $requestLevel = $request->input('level');
        $requestName = $request->input('name');
        $allVertex = Tree::all();
        for($i=0;$i<count($allVertex);$i++){
            if($allVertex[$i]->name == $requestName){
                $requestName = $requestName.' new';
            }
            if($allVertex[$i]->position == $requestPosition && $allVertex[$i]->level == $requestLevel){
                for($j=0;$j<count($allVertex);$j++) {
                    $oldVertexPosition = $allVertex[$j]->position + 1;
                    $oldVertexLevel = $allVertex[$j]->level;
                    $oldVertexId = $allVertex[$j]->id;
                    $oldVertexName = $allVertex[$j]->name;
                    $updateVertex = Tree::find($oldVertexId);
                    $updateVertex->name = $oldVertexName;
                    $updateVertex->position = $oldVertexPosition;
                    $updateVertex->level = $oldVertexLevel;
                    $updateVertex->save();
                    $requestPosition++;
                }
            }
        }
        $add = new Tree([
            'name' => $requestName,
            'position' => $requestPosition,
            'level' => $requestLevel
        ]);
        $add->save();
        $result="Add vertex :)";
        return $result;
    }

}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/TreeController.php
<?php

namespace App\Http\Controllers;

use App\Edges;
use Illuminate\Http\Request;
use App\Tree;

class TreeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function edge(Request $request)
    {
        $parentVertex = $request->parentVertex;
        $forParent = $request->get('forParent');
        if (isset($parentVertex) && isset($forParent)) {
            $edges = new Edges([
                'id_vertex_child' => $parentVertex,
                'id_vertex_parent' => $forParent
            ]);
            $edges->save();
        }
        else {
            return redirect('/trees')->with('info', 'Check values new edge.');
        }

        return redirect('/trees')->with('info', 'Edges saved!');
    }

    public function connect(){
        $vertices = Tree::all();
        return view('trees.connect', compact('vertices'));
    }

    public function jsTree()
    {
        $trees = Tree::all();
        $edges = Edges::all();
        return view('trees.tree', compact('trees','edges'));
    }

    public function index()
    {
        $trees = Tree::allPositionDescending();

        return view('trees.index', compact('trees'));
    }

    public function sortByLevel()
    {
        $trees = Tree::allLevelDescending();

        return view('trees.index', compact('trees'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('trees.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'=>'required',
            'position'=>'required',
            'level'=>'required'
        ]);
        $result=Tree::addWithChangePositionOld($request);
        return redirect('/trees')->with('info', $result);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $tree = Tree::find($id);
        return view('trees.edit', compact('tree'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name'=>'required',
            'position'=>'required',
            'level'=>'required'
        ]);

        $tree = Tree::find($id);
        $tree -> delete();
        $result=Tree::addWithChangePositionOld($request);
        return redirect('/trees')->with('info', $result);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $contact = Tree::find($id);
        $contact -> delete();

        return redirect('/trees')->with('info', 'Tree deleted!');
    }
}

resources/views/trees/connect.blade.php
@extends('welcome')

@section('main')
    <div class="row">
        <div class="col-sm-4"><h1 class="display-3">Connect the Vertex by Edge</h1></div>
        <div class="col-sm-8">
            <div>
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div><br />
                @endif
                <form method="post" action="/trees/connect">
                    @csrf
                    <div class="form-group">
                        <label for="forParent">Vertex:</label>
                        <select id="forParent" class="form-control" name="forParent">
                            <option value="" selected></option>
                            @foreach($vertices as $vertex)
                                <option value="{{$vertex->id}}">{{$vertex->name}}</option>
                            @endforeach
                        </select>
                        <label for="parentVertex">Parent of Vertex:</label>
                        <select id="parentVertex" class="form-control" name="parentVertex">
                            <option value="" selected></option>
                        </select>
                    </div>
                    <button type="submit" class="btn btn-success">Add edge</button>
                </form>
            </div>
        </div>
    </div>
    <script>
        class addEdge{
            static getValue() {
                const arrayTree = {!! $vertices !!};
                console.log(arrayTree);
                //console.log("Otwieramy nawigacje");
                let strVertex = selectForm.selectedIndex-1;
                console.log(strVertex);
                let levelParentVertex;
                levelParentVertex = arrayTree[strVertex]['level']-1;
                console.log(levelParentVertex);
                if(strVertex>=0)
                {
                    console.log(levelParentVertex);
                    const parrentOfVertexTree = new Array();
                    for(let i = 0; i < Object.keys(arrayTree).length; i++) {
                        if(arrayTree[i]['level']==levelParentVertex)
                        {
                            parrentOfVertexTree.push(arrayTree[i]);
                        }
                    }
                    //console.log(Object.keys(parrentOfVertexTree));
                    let select = document.getElementById("parentVertex");
                    document.getElementById("parentVertex").innerHTML = ' ';
                    for(let i = 0; i < Object.keys(parrentOfVertexTree).length; i++) {
                        //console.log(parrentOfVertexTree[i]);
                        //console.log(parrentOfVertexTree[i]['name']);
                        select.options[select.options.length] = new Option(parrentOfVertexTree[i]['name'], parrentOfVertexTree[i]['id']);
                    }
                    //return parrentOfVertexTree;
                    //alert(strVertex);
                }
            }
        }
        const selectForm = document.getElementById( 'forParent' );
        selectForm.onclick = addEdge.getValue;
    </script>
@endsection

resources/views/trees/create.blade.php
@extends('welcome')

@section('main')
    <div class="row">
        <div class="col-sm-4"><h1 class="display-3">Add element to the Tree</h1></div>
        <div class="col-sm-8">
            <div>
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div><br />
                @endif
                <form method="post" action="{{ route('trees.store') }}">
                    @csrf
                    <div class="form-group">
                        <label for="name">Name:</label>
                        <input type="text" class="form-control" name="name"/>
                    </div>

                    <div class="form-group">
                        <label for="level">Level:</label>
                        <input type="number" class="form-control" name="level"/>
                    </div>

                    <div class="form-group">
                        <label for="position">Position:</label>
                        <input type="number" class="form-control" name="position"/>
                    </div>
                    <button type="submit" class="btn btn-success">Add vertex</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/trees/edit.blade.php
@extends('welcome')
@section('main')
    <div class="row">
        <div class="col-sm-4"><h1 class="display-3">Update element in the Tree</h1></div>
        <div class="col-sm-8">

            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
                <br />
            @endif
            <form method="post" action="{{ route('trees.update', $tree->id) }}">
                @method('PATCH')
                @csrf
                <div class="form-group">
                    <label for="first_name">Name:</label>
                    <input type="text" class="form-control" name="name" value={{ $tree->name }} />
                </div>

                <div class="form-group">
                    <label for="last_name">Position:</label>
                    <input type="text" class="form-control" name="position" value={{ $tree->position }} />
                </div>

                <div class="form-group">
                    <label for="email">Level:</label>
                    <input type="text" class="form-control" name="level" value={{ $tree->level }} />
                </div>
                <button type="submit" class="btn btn-primary">Update</button>
            </form>
        </div>
    </div>
@endsection

resources/views/trees/index.blade.php
@extends('welcome')

@section('main')
    <div class="row">
        <div class="col-sm-6">
            <h1 class="display-3">Vertex manager</h1>
        </div>
        <div class="col-sm-6 justify-content-end">
            @if(session()->get('info'))
                <div class="alert alert-info">
                    {{ session()->get('info') }}
                </div>
            @endif
        </div>
        <div class="col-md-10">
            <table class="table table-striped">
                <thead>
                <tr>
                    <td>ID</td>
                    <td>Name</td>
                    <td>Position</td>
                    <td>Level</td>
                    <td colspan = 2>Actions</td>
                </tr>
                </thead>
                <tbody>
                @foreach($trees as $tree)
                    <tr>
                        <td>{{$tree->id}}</td>
                        <td>{{$tree->name}}</td>
                        <td>{{$tree->position}}</td>
                        <td>{{$tree->level}}</td>
                        <td>
                            <a href="{{ route('trees.edit',$tree->id)}}" class="btn btn-primary">Edit</a>
                        </td>
                        <td>
                            <form action="{{ route('trees.destroy', $tree->id)}}" method="post">
                                @csrf
                                @method('DELETE')
                                <button class="btn btn-danger" type="submit">Delete</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
        <div class="col-md-2">
            <form method="get" action="/trees/sortByPosition">
                <button class="btn btn-info" type="submit">Sort by Position</button>
            </form>
            <form method="get" action="/trees/sortByLevel">
                <button class="btn btn-info" type="submit">Sort by Level</button>
            </form>
        </div>
    </div>
@endsection

resources/views/trees/tree.blade.php
@extends('welcome')

@section('main')
    <div class="row">
        <div class="col-sm-12 justify-content-center align-content-center">
            <canvas></canvas>
        </div>
    </div>
    <script type="text/javascript">
        const arrayTree = {!! $trees !!};
        //console.log(arrayTree[0]['id']);
        //console.log(Object.keys(arrayTree).length);

        const canvas = document.querySelector('canvas');
        fitToContainer(canvas);
        const ctx = canvas.getContext('2d');
        const wCanvas = canvas.width;
        const hCanvas = canvas.height;
        ctx.clearRect(0, 0, wCanvas, hCanvas);

        function fitToContainer(canvas){
            // Make it visually fill the positioned parent
            canvas.style.width ='100%';
            // ...then set the internal size to match
            canvas.width  = canvas.offsetWidth;
            canvas.height = document.documentElement.clientHeight-100;
        }

        function ball(id, x, y, text){
            this.x = x;
            this.y = y;
            this.text = text;
            this.radius = 35;
            this.color = '#fff';
            this.id = id;
            this.draw = function(){
                ctx.beginPath();
                ctx.arc(this.x, this.y, this.radius, 0, 2*Math.PI, false);
                ctx.fillStyle = '#007bff';
                ctx.fill();
                ctx.closePath();
                ctx.beginPath();
                ctx.fillStyle = '#343a40';
                ctx.fillText(this.text, this.x-25, this.y-30);
                ctx.fill();
                ctx.closePath();
            }
        }

        function line(xs, ys, xf, yf){
            this.xs = xs;
            this.ys = ys;
            this.xf = xf;
            this.yf = yf;
            this.draw = function(){
                ctx.beginPath();
                ctx.moveTo(xs,ys);
                ctx.lineTo(xf,yf);
                ctx.strokeStyle="green";
                ctx.stroke();
            }
        }
        const edgesTree = {!! $edges !!};
        const balls = [];

        function renderBalls(){
            let x = 0;
            let y = 0;
            let text = '';
            let id = 0;
            for(let i = 0; i < Object.keys(arrayTree).length; i++) {
                    y = 50 + arrayTree[i]['level']*150;
                    x = 50 + arrayTree[i]['position']*150;
                    text = arrayTree[i]['name'];
                    id = arrayTree[i]['id'];
                    console.log(text);
                    balls[i] = new ball(id, x, y, text);
                    balls[i].draw();
            }
        }

        function renderLine(){
            const lineTree = [];
            for(let ed = 0; ed < Object.keys(edgesTree).length; ed++) {
                lineTree[ed] = [];
                for(let ba = 0; ba < Object.keys(balls).length; ba++) {
                    if (edgesTree[ed]['id_vertex_child'] == balls[ba]['id']) {
                        lineTree[ed]['xs'] = balls[ba]['x'];
                        lineTree[ed]['ys'] = balls[ba]['y'];
                    }
                    if (edgesTree[ed]['id_vertex_parent'] == balls[ba]['id']) {
                        lineTree[ed]['xf'] = balls[ba]['x'];
                        lineTree[ed]['yf'] = balls[ba]['y'];
                    }
                }
                line[ed] = new line(lineTree[ed]['xs'],lineTree[ed]['ys'],lineTree[ed]['xf'],lineTree[ed]['yf']);
                line[ed].draw();
            }
        }
        function welcomeText(text){
            ctx.font = 'normal bold 60px sans-serif';
            ctx.textAlign = 'center';
            ctx.textBaseline = 'middle';
            ctx.fillText(text, canvas.width/2, canvas.height/4);
        }

        document.addEventListener("click", function() {
            ctx.font = 'normal bold 14px sans-serif';
            ctx.clearRect(0, 0, canvas.width, canvas.height);
            renderBalls();
            renderLine();
        });
        welcomeText("Click to run view");
        console.log(balls);

    </script>
@endsection